# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "uhci_hcd" "ehci_pci" "ahci" "virtio_pci" "virtio_scsi" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/d2b0bcb5-42e0-4f37-b3e7-3c23eae54345";
      fsType = "ext4";
    };

  fileSystems."/tank" = {
      device = "/dev/sdb";
      fsType = "btrfs";
      options = [ "defaults" "compress=zstd:1" "noatime" "space_cache=v2" "degraded" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/f41bdf18-434b-4163-99c0-8e61185d9a00"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
