# Do not modify this file! 1t was generated by
# and may be overwritten by future invocations. Please make changes
# to /etc/nixos/configuration . nix instead .
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [(modulesPath + "/installer/scan/not—detected.nix")];

  boot.initrd.availableKernelModules = [ "ehci_pci" "ahci" "xhci_pci" "usbhid" "usb_storage" "sb_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
  {
    device = "/dev/disk/by-uuid/6adb5221-32e0-4ab9-b1a7-49ce7c3c821d";
    fsType = "ext4";
  };

  fileSystems."/boot" =
  {
    device = "/dev/disk/by-uuid/AAE1-5052";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  }

  swapDevices =
  [
    {
      device = "/dev/disk/by-uuid/59eba817-d0f1-45d0-bd51-ba709dc94511";
    }
  ]

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
